const games=[
{id:'snake',title:'Neon Snake',category:'arcade',description:'Grow, turn fast and survive the neon arena.',path:'games/snake.html',cover:'cover-snake',emoji:'🐍',tag:'Arcade',meta:'Fast reflexes',rank:1,new:false},
{id:'runner',title:'Pixel Runner',category:'skill',description:'Jump over obstacles and keep your endless run alive.',path:'games/runner.html',cover:'cover-runner',emoji:'🏃',tag:'Skill',meta:'Endless run',rank:2,new:true},
{id:'blaster',title:'Astro Blaster',category:'action',description:'Blast incoming meteors and survive wave after wave.',path:'games/blaster.html',cover:'cover-blaster',emoji:'🚀',tag:'Action',meta:'Space shooter',rank:3,new:true},
{id:'jump',title:'Sky Hopper',category:'skill',description:'Bounce higher and higher across moving platforms.',path:'games/jump.html',cover:'cover-jump',emoji:'☁️',tag:'Skill',meta:'Highscore chase',rank:4,new:true},
{id:'dodge',title:'Dodge Rush',category:'action',description:'Move fast, dodge red hazards and collect bonus stars.',path:'games/dodge.html',cover:'cover-dodge',emoji:'⚡',tag:'Action',meta:'Quick rounds',rank:5,new:true},
{id:'merge',title:'Tile Merge',category:'puzzle',description:'Combine matching tiles and chase the 2048 tile.',path:'games/2048.html',cover:'cover-merge',emoji:'🧠',tag:'Puzzle',meta:'Think ahead',rank:6,new:false},
{id:'pong',title:'Brick Bounce',category:'classic',description:'Break every brick without letting the ball escape.',path:'games/pong.html',cover:'cover-pong',emoji:'🟣',tag:'Classic',meta:'Arcade classic',rank:7,new:false}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const state={category:'all',query:'',sort:'featured',favorites:store.get('gu-favorites',[]),recent:store.get('gu-recent',[])};
function save(){store.set('gu-favorites',state.favorites);store.set('gu-recent',state.recent)}
function game(id){return games.find(g=>g.id===id)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
function launch(id){const g=game(id);if(!g)return;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);save();renderRecent();location.href=g.path}
function toggleFavorite(id,e){e?.stopPropagation();state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderGames();toast(state.favorites.includes(id)?'⭐ Added to favorites':'Removed from favorites')}
function visibleGames(){let list=games.filter(g=>(state.category==='all'||g.category===state.category)&&(`${g.title} ${g.description} ${g.tag}`.toLowerCase().includes(state.query.toLowerCase())));if(state.sort==='az')list.sort((a,b)=>a.title.localeCompare(b.title));else if(state.sort==='new')list.sort((a,b)=>Number(b.new)-Number(a.new)||a.rank-b.rank);else list.sort((a,b)=>a.rank-b.rank);return list}
function card(g,i){const fav=state.favorites.includes(g.id);return `<article class="game-card" data-game="${g.id}" tabindex="0" style="--i:${i}"><div class="game-cover ${g.cover}"><div class="cover-pattern"></div><div class="game-emoji">${g.emoji}</div><span class="game-badge">${g.new?'NEW • ':''}${g.tag.toUpperCase()}</span><span class="play-pop">▶</span></div><div class="game-info"><div class="title-row"><h3>${g.title}</h3><button class="fav ${fav?'on':''}" data-fav="${g.id}" aria-label="Favorite">${fav?'★':'☆'}</button></div><p>${g.description}</p><div class="game-meta"><span>${g.meta}</span><span>PLAY →</span></div></div></article>`}
function renderGames(){const list=visibleGames();$('#gameGrid').innerHTML=list.map(card).join('');$('#emptyState').classList.toggle('hidden',list.length>0);$('#resultText').textContent=`${list.length} game${list.length===1?'':'s'} ready`;$$('[data-game]').forEach(el=>{el.onclick=()=>launch(el.dataset.game);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();launch(el.dataset.game)}}});$$('[data-fav]').forEach(el=>el.onclick=e=>toggleFavorite(el.dataset.fav,e))}
function renderRecent(){const items=state.recent.map(game).filter(Boolean);$('#continueSection').classList.toggle('hidden',items.length===0);$('#recentRow').innerHTML=items.map(g=>`<div class="recent-card" data-recent="${g.id}"><div class="recent-icon">${g.emoji}</div><div><strong>${g.title}</strong><small>Continue playing →</small></div></div>`).join('');$$('[data-recent]').forEach(el=>el.onclick=()=>launch(el.dataset.recent))}
function random(){const list=visibleGames();launch((list.length?list:games)[Math.floor(Math.random()*(list.length?list.length:games.length))].id)}
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim();renderGames()});
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('#searchInput')){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape'){$('#searchInput').blur()}});
$$('[data-category]').forEach(btn=>btn.onclick=()=>{$$('[data-category]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.category=btn.dataset.category;renderGames();document.querySelector('#allGames').scrollIntoView({behavior:'smooth',block:'start'})});
$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderGames()};$('#randomBtn').onclick=random;$('#playRandom').onclick=random;$('#clearRecent').onclick=()=>{state.recent=[];save();renderRecent();toast('History cleared')};$('#favoritesBtn').onclick=()=>{const favs=games.filter(g=>state.favorites.includes(g.id));if(!favs.length){toast('No favorites yet ⭐');return}state.query='';state.category='all';$('#searchInput').value='';renderGames();$('#gameGrid').innerHTML=favs.map(card).join('');$$('[data-game]').forEach(el=>el.onclick=()=>launch(el.dataset.game));$$('[data-fav]').forEach(el=>el.onclick=e=>toggleFavorite(el.dataset.fav,e));$('#resultText').textContent=`${favs.length} favorite game${favs.length===1?'':'s'}`;$('#allGames').scrollIntoView({behavior:'smooth'})};$('#resetSearch').onclick=()=>{state.query='';state.category='all';$('#searchInput').value='';$$('[data-category]').forEach((x,i)=>x.classList.toggle('active',i===0));renderGames()};
renderGames();renderRecent();